### ISSUE TITLE
When to update?

### ISSUE THREAD

**Issue by RainoutOvO** [LiteLDev-LXL/LXLEssential#5]
I having been waiting for your update for more than a month!!

**Comment by Xiaoliang-dev** [comment]
https://www.mcbbs.net/forum.php?mod=viewthread&tid=1324247 自己去看，他都被查封了，因为植入后门

**Comment by Xiaoliang-dev** [comment]
https://www.mcbbs.net/forum.php?mod=viewthread&tid=1324247 went to see for himself, he was all seized because of the implantation of a backdoor

**Comment by RainoutOvO** [comment]
> https://www.mcbbs.net/forum.php?mod=viewthread&tid=1324247 went to see for himself, he was all seized because of the implantation of a backdoor

Thanks
